### ISSUE TITLE
What about release management?

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-cucumberjvm#1]
What about it in team? Who make releases and how it deploys to maven central?

**Comment by vania-pooh** [comment]
@clicman we have a Teamcity instance: http://teamcity.qatools.ru/ and it does all the stuff itself. Let's create a build for this project.

**Comment by clicman** [comment]
Sounds good. But I have no permissions. Could you create the build or give me me appopreate privelegies on this instance?

**Comment by vania-pooh** [comment]
@clicman sent all this stuff to your email. Pull requests should be built automatically. After merging any PR a new snapshot should be sent to Sonatype. Release build should be certainly run manually.

**Comment by vania-pooh** [comment]
@clicman please check that it works and reopen in case of issues.
