### ISSUE TITLE
Period in the step parameter breaks test case name in the report and report displays only part after the period

### ISSUE THREAD

**Issue by GreenTeaCake** [allure-framework/allure-cucumberjvm#10]
Hi. I'm not sure if it is allure-cucumber-jvm-adaptor, allure-maven-plugin or allure-report-builder issue. But I gonna raise the ticket here.

**_Cucumber feature**_

``` gerkhin
Feature: Check step parameters displaying in Allure report
  Scenario: Check parameter displaying
    Given https://www.google.com string param in the beginning
    Given string param https://www.google.com in the middle
    Given string param in the end https://www.google.com
```

**_Report**_
![screen shot 2015-03-10 at 16 19 01](https://cloud.githubusercontent.com/assets/167279/6584401/62048336-c741-11e4-8b69-1969800557c6.png)

The period in the step parameter breaks test case name and report displays only part after the period.

**Comment by vania-pooh** [comment]
@clicman please check that case name like above goes to test case title and not name.

**Comment by clicman** [comment]
@grumblerchester @vania-pooh As I remeber it was some talks about testcase.title in [allure core #442](https://github.com/allure-framework/allure-core/issues/442).
