### ISSUE TITLE
Where to get ${aspectj.version} ?

### ISSUE THREAD

**Issue by Simon-Kaz** [allure-framework/allure-cucumberjvm#16]
Hey, the readme states that all I need is to copy the maven dependency and build, but when I do, I get an error on ${aspectj.version} as It cannot be resolved (as its not set anywhere).

**Comment by Simon-Kaz** [comment]
I found it in the pom file for the project, you might want to update your readme/guide :)

https://github.com/allure-framework/allure-cucumber-jvm-adaptor/blob/63fa562f881aecf125a44ee744955d5fa21d29c3/pom.xml#L64

**Comment by clicman** [comment]
Usually you should not to point in in child projects. Will see it tomorrow.
