### ISSUE TITLE
Tests suites and Steps broken if an URL is pressent, using cucumber-jvm-adaptor

### ISSUE THREAD

**Issue by jmunozrubio** [allure-framework/allure-cucumberjvm#18]
With the next Feature:

```
@autocorrect
Feature: Automatically correct mistyped search terms

  Scenario: Enter search term and who knows...
    Given I am on the website http://www.google.com
    When I submit the search term leda-mc
    And accept the first search result
    Then I should be on the page http://www.leda-mc.com/

  Scenario Outline: Enter search term and view related images
    Given I am on the website http://www.google.com
    When I submit the search term <search>
    And accept the first search result
    Then I should be on the page <page>

    Examples:
        | search     | page                        |
        |  opencredo |  https://www.opencredo.com/ |
        |  leda-mc   |  http://www.leda-mc.com/    |
```

In xUnit section titles for Test Suites and Steps appears just with "Com" (string after last dot)

See attached screenshot
![allure_dashboard_-_2015-10-08_11 40 40](https://cloud.githubusercontent.com/assets/885886/10362896/7c0b7ff2-6db1-11e5-86ae-98f171aca4db.png)

**Comment by clicman** [comment]
It is not an adaptor bug, but allure-core`s one. See #14 for details. I will mark this as duplicate.

**Comment by jmunozrubio** [comment]
Thanks for your quickly answer, but just one question: if all issues related with dot problems in titles are closed ¿means that will not be fixed?

**Comment by clicman** [comment]
@jmunozrubio It is planned to 2.0 milestone https://github.com/allure-framework/allure-core/issues/408
 So you culd vote for downgrade feature milestone in that issue. Or build your own https://github.com/allure-framework/allure-core/tree/master/allure-report-face and fix it there (it should be simple to implement).

**Comment by jmunozrubio** [comment]
Ah!! Ok perfect. I din't know about the new planned milestone.

Thanks again.

**Comment by baev** [comment]
> It is not an adaptor bug, but allure-core`s one. See #14 for details. I will mark this as duplicate.

It is an adaptor problem, you should use `title` instead of `name`

**Comment by clicman** [comment]
Oh wow! I will take a look tomorrow.

**Comment by clicman** [comment]
Realeased 1.5 version.

**Comment by clicman** [comment]
Problem needs additional investigation.
