### ISSUE TITLE
1.5.1 Release

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-cucumberjvm#20]
@vania-pooh @baev 
Hi guys! I ve released 1.5 version via jenkins deploy job, but it didnt appear on public repos.
(see https://oss.sonatype.org/#nexus-search;quick~allure-cucumber-jvm-adaptor).
Should it aproved by someone or I`ve missed something?

**Comment by clicman** [comment]
Update to 1.5.1 version.

**Comment by vania-pooh** [comment]
@clicman will approve it.

**Comment by clicman** [comment]
@vania-pooh Thanks!
