### ISSUE TITLE
Steps are being displayed as tests

### ISSUE THREAD

**Issue by Jiwari** [allure-framework/allure-cucumberjvm#21]
The report is displaying every step as a "test", this creates confusion as there can  be displayed 200 tests, when there actually only 20 cucumber Scenarios.

I'm not sure if this is suppose to work like this, but my vision is that the report should display on the graphs the cucumber "Scenarios" that failed/passed/broken instead of each separate stepdefinition.

**Comment by clicman** [comment]
I agree with you but this behaviour comes from cucumber-jvm-junit plugin.

**Comment by clicman** [comment]
I decided to reopen this issue. I have some thouts how to implement it.

**Comment by clicman** [comment]
@baev I need some support to analyze it.
My implimentation plan is to replace suiteStarted/Finished/.. events by TestCaseStarted/Finished/... and replace TestCaseStarted/Finished/.. by StepStarted/Finished/.. 
But as I understand, I cannot fully manage steps statuses - only last one. It will cause multithreading issues. 
Any Ideas how to deal with it? Maybe is it possible to expose steps management api in core as it for test cases for example, to magange steps by some unique identifier?

**Comment by clicman** [comment]
As alternative it can be fixed via cucumber-jvm patching. See https://github.com/cucumber/cucumber-jvm/pull/588 for details.

**Comment by clicman** [comment]
Will be fixed while [PR#36](https://github.com/allure-framework/allure-cucumber-jvm-adaptor/pull/36) merged

**Comment by nicolas-duvivier** [comment]
That's nice ! Good job

**Comment by clicman** [comment]
Fixed in master. Will available in 1.6 release
