### ISSUE TITLE
dots (.) in Cucumber feature cause Allure report to truncate certain labels

### ISSUE THREAD

**Issue by dhaerinck** [allure-framework/allure-cucumberjvm#22]
Hi, 

I'm enjoying using Allure for reporting, but I have a simple problem and I don't seem to find a solution on the web other than "don't use dots", which is of course, not possible.

Thing is this: Often in my feature file i have a parameter containing a dot, sometimes this is a url, sometimes it is a username. When I generate my allure reports, all is generated correctly and I have the right output, except that the steps in the "Story" page under "Behaviors" tab are truncated whenever a dot is encountered. If I select this faulty step, the title in the detail is also truncated, but the "Testcase" item displays the step correctly.

Given, for example, a step named as follows:

And I login as "test.user451" with password "Test4ThisUser980"

My test case will be displayed as follows:

user451" with password "Test4ThisUser980"

In the detailed view, I will have both correct AND incorrect display.

Namely, the title (with the little green icon next to it) will be displayed incorrectly, but the "Testcase:" value right above it will display the step perfectly. I can only assume this is a bug, and it should be quite easy to reproduce, as it happens in every step of every scenario that contains a dot.

I've tested this on both Firefox and Chrome, so it is the same for both. There are no errors in rendering, so this problem is situated on the server side. No errors in the server side logs either, however.

**Comment by clicman** [comment]
What version of adaptor did you use? It should be fixed in 1.5.1 version.

**Comment by dhaerinck** [comment]
I'm using 1.4. Thanks for the info!
