### ISSUE TITLE
Issue with Test case timings

### ISSUE THREAD

**Issue by dhaerinck** [allure-framework/allure-cucumberjvm#23]
Not sure if it fits in this project, but I don't see 
Problem : All the Test cases (Cucumber steps) have a duration of 0/1ms.

I have two projects in parallel, one running Allure with a normal JUnit and Selenium 2, the other one adding Cucumber to the mix and using specification by example to define the test cases instead of the unit test case performing the steps.

@Steps are naturally replaced by @Given, @When, @Then.

Problem that presents itself to me is in the cucumber project using allure-cucumber-jvm-adaptor (other tech is the same except cucumber is added and the adaptor of course). 

In the other tests, I use fluent logic such that every test method that triggers a page redirect creates the new page and returns it. In the cucumber tests, I just run the tests as-is because I don't need to create the pages, the steps are run whichever page they're in, Ive defined an implicit wait in the webdriver provider and a PageFactory.initElements() in the Page object superclass. Steps are defined using @Step and the timing is relatively accurate. 

In the cucumber project, I run the tests with Page Objects as well, but I don't create the Page Objects manually, I have the test runner run them and call PageFactory.initElements() in the constructor. 

Ive tried removing the PageFactory.initElements() and wait explicitly for these elements in the test methods themselves, so the waiting would occur inside the test methods, but it doesn't seem to matter. Only failing steps take longer than 1 ms, and that is only because I take a screenshot and attach a log when it fails. 

The Test Suites (Cucumber scenario) specifies the correct timing, it's only the specific steps (Test Cases) that don't.

**Comment by clicman** [comment]
Look at this PR in cucumber-jvm project https://github.com/cucumber/cucumber-jvm/pull/825
It fixes timing issues.
So you can build your version of cucumer-jvm (mergin this PR locally).
When it done - merge this branch in cucumber-jvm-adaptor: https://github.com/allure-framework/allure-cucumber-jvm-adaptor/tree/cucmber-timing-fix

And you`ll get right timings. I can not release fix because it is cucumer-jvm bug :(
But you can drop some vote in pull request and probably it will more chanses to be merged in upstream.

**Comment by dhaerinck** [comment]
Alright, I'll do that! Thanks man!

**Comment by nicolas-duvivier** [comment]
I'm not used to the process here.
Is there a maven dependency for this fix ?

Regards

**Comment by clicman** [comment]
@nicolas-duvivier  you can build your own jars and install it ti local maven repository.

**Comment by jaheikki** [comment]
@clicman Is this timing issue still not corrected? I see these "duration not showing correct values" in Allure report with Cucumber-jvm. I have cucumber-java (and it's dependencies) version 1.2.5 and allure-cucumber-jvm-adaptor version 1.5.1. I can see from the earlier discussion that cuccumber-jvm was the bottleneck in this problem. But cucumber/cucumber-jvm#825 is closed and still problem not solved with latest maven dependencies...?

**Comment by jaheikki** [comment]
@clicman I reply to myself, Cucumber option "--allow-started-ignored"  (https://github.com/cucumber/cucumber-jvm/pull/1002) seems solving "duration not showing correct values" issue in Allure report. However new small bug comes in with that new option, the pending status (not executed) testcases are somehow duplicated in the Allure report, but that is quite small problem...

**Comment by clicman** [comment]
@jaheikki  Yes, I know what it solves the problem. But I will on the go to switch allure to cucumber plugin. And all of issues should be fixed by this.

**Comment by jaheikki** [comment]
@clicman Could you please describe further about your plans, so what do you mean by "switch allure to cucumber plugin"? Are you planning to abandon Allure reports by other reports...?

**Comment by clicman** [comment]
@jaheikki yes, take a look at https://github.com/kirlionik/allure-cucumber-plugin
So it will based on this code. Initial plugin has problems with i18n (which I fixed in my branch), but if you using English only in your scenarios, you can test it now from their repository.

**Comment by jaheikki** [comment]
@clicman Thanks a lot for this information! Yes I will be using English only in scenarios. I will try the plugin asap :)

**Comment by clicman** [comment]
Fixed in master. Will available in 1.6 release
