### ISSUE TITLE
Error on build - java.lang.NoClassDefFoundError: ru/yandex/qatools/allure/AllureUtils

### ISSUE THREAD

**Issue by robertgates55** [allure-framework/allure-cucumberjvm#30]
Adding the dependency to my pom (but not then invoking it anywhere):
    <dependency>
      <groupId>ru.yandex.qatools.allure</groupId>
      <artifactId>allure-cucumber-jvm-adaptor</artifactId>
      <version>1.5.1</version>
    </dependency>

results in the following when trying to build my project:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.118 s
[INFO] Finished at: 2016-04-22T15:14:18+01:00
[INFO] Final Memory: 28M/286M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project Frameworkium: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: ru/yandex/qatools/allure/AllureUtils
[ERROR] at ru.yandex.qatools.allure.testng.AllureTestListener.onStart(AllureTestListener.java:66)
[ERROR] at org.testng.TestRunner.fireEvent(TestRunner.java:1243)
[ERROR] at org.testng.TestRunner.beforeRun(TestRunner.java:640)
[ERROR] at org.testng.TestRunner.run(TestRunner.java:613)
[ERROR] at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[ERROR] at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[ERROR] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[ERROR] at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[ERROR] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[ERROR] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[ERROR] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
[ERROR] at org.testng.TestNG.run(TestNG.java:1032)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: ru.yandex.qatools.allure.AllureUtils
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] ... 19 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

What am I doing wrong and what could be causing this?

**Comment by clicman** [comment]
adaptor doesn`t support TestNg only JUnit one.
