### ISSUE TITLE
[RU] gradle + allure + cucumber-jvm

### ISSUE THREAD

**Issue by jalona** [allure-framework/allure-cucumberjvm#31]
Добрый день.

В maven это делается через surefire с указанием CustomAllureRunListener  и подтягиванием 

```
<includes>
     <include>**/*AT.java</include>
</includes>
```

согласно примеру из 
https://github.com/allure-examples/allure-cucumber-jvm-example

Имеется ли возможность реализовать запуск тестов в связке
gradle + allure + cucumber-jvm ?

https://github.com/allure-framework/allure-core/issues/847

**Comment by clicman** [comment]
Почему бы просто не добавить листенер в тестируемый проект и не передать его через FQDN?
как здесь: https://github.com/allure-examples/allure-cucumber-jvm-example/blob/master/pom.xml#L45
