### ISSUE TITLE
Duration time for Cucumber Test Scenario displays as "0"

### ISSUE THREAD

**Issue by mmuntakim15** [allure-framework/allure-cucumberjvm#34]
Hello,
Total duration time for individual test scenario is not being calculated correctly. For example if I have three test steps where each steps took 1 Second then Scenario duration time should display duration as 3 Second. Please see the attached screenshot for further details.

Again any help will be appreciated.

![allurescreenshot](https://cloud.githubusercontent.com/assets/11964005/20230821/ef4fedbc-a82b-11e6-82c2-9a7c16aaf424.png)

**Comment by nicolas-duvivier** [comment]
Duplicate --> #23
