### ISSUE TITLE
Lost permissions to project

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-cucumberjvm#35]
@baev hi!

Just tried to push new branch and issued "Access Denied". Give me access please.

**Comment by baev** [comment]
@clicman sorry for the delay. Check this out https://github.com/allure-framework/allure-cucumber-jvm-adaptor/invitations

**Comment by clicman** [comment]
@baev  Yes. Now I have permissions. Thanks.
What about release flow? Something changed since last year? What steps to publish release?

**Comment by baev** [comment]
create a ticket and I'll release

**Comment by clicman** [comment]
Ok. Got it!
