### ISSUE TITLE
Where is 1.6 release?

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-cucumberjvm#40]
@baev Hi! I cannot find 1.6 release on oss.sonatype.org nor search.maven.org.
Where was it stuck?

Anyway let's publish [1.6.1](https://github.com/allure-framework/allure-cucumber-jvm-adaptor/releases/tag/untagged-ce4d577cae183f08f626)

**Comment by baev** [comment]
Both 1.6 and 1.6.1 should be available in maven central within a hour

**Comment by baev** [comment]
https://repo.maven.apache.org/maven2/ru/yandex/qatools/allure/allure-cucumber-jvm-adaptor/

**Comment by clicman** [comment]
Thank you!
