### ISSUE TITLE
cucumber.options is configured twice

### ISSUE THREAD

**Issue by dstoianov** [allure-framework/allure-cucumberjvm#43]
I got a warning message when i configured cucumber as here in tutorial
`[WARNING] The system property cucumber.options is configured twice! The property appears in <argLine/> and any of <systemPropertyVariables/>, <systemProperties/> or user property.
`
I run my tests from command line like 
> mvn clean verify -U -Dspring.profiles.active=qa -Dcucumber.options='--tags ~@ignore --tags @aux-user --tags @env_qa --plugin json:target/cucumber/report.json'
So, as the result no any test artifacts.

**WORKAROUND** use old style with `AllureRunListener` and add it to `pom.xml` as listener

**Comment by clicman** [comment]
Hi! It's bad idea to workaround it by this way. The warning says you what you use options from several places (from commandline in your case).
To properly use new adaptor you should remove argline from pom.xml and pass it via commandline like follows:
```
mvn clean verify -U -Dspring.profiles.active=qa -Dcucumber.options='--tags ~@ignore --tags @aux-user --tags @env_qa --plugin json:target/cucumber/report.json --plugin ru.yandex.qatools.allure.cucumberjvm.AllureReporter'
```

And do not use old AllureRunListener it was deprecated and will be removed in future.
