### ISSUE TITLE
Not able to show data tables in background section of the report 

### ISSUE THREAD

**Issue by punitbisht** [allure-framework/allure-cucumberjvm#44]
Hi , 

cucumber-jvm adaptor is not displaying data tables in background section of feature report .
I am trying something like this 
<img width="1173" alt="screen shot 2017-03-03 at 9 31 27 am" src="https://cloud.githubusercontent.com/assets/19594631/23557151/a8b8f4ea-fff4-11e6-9958-aca16726d9c9.png">

**Comment by clicman** [comment]
Fixed in 1.6.3. Wait for release via #48
