### ISSUE TITLE
Publish release 1.6.3

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-cucumberjvm#48]
@baev let's release it https://github.com/allure-framework/allure-cucumberjvm/releases/tag/1.6.3

**Comment by clicman** [comment]
@baev ping.

**Comment by eroshenkoam** [comment]
Done: https://oss.sonatype.org/#nexus-search;quick~allure-cucumber-jvm-adaptor

**Comment by clicman** [comment]
Thanks
